Templeton
Templeton
N2024


04/11/2023 10:46:43
Syringe Injection

FID
2m 2mmID ShinCarbonST 80/100
Argon at 35psi
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_200deg.tem
Channel1.evt
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_iso_FID_comps.cpt
60.0,40.0,   10.00, 1.000, 0.500,0
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_Ar_iso200_35psi.CON
11Apr23_TAC_FID_03.CHR
blank
TC


