Templeton
Templeton
N2024


01/11/2023 16:58:05
Syringe Injection

FID
2m 2mmID ShinCarbonST 80/100
Argon at 35psi
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_200deg.tem
Channel1.evt
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_iso_FID_comps.cpt
60.0,40.0,   10.00, 1.000, 0.500,0
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_Ar_iso200_35psi.CON
11JAN23FID_TC_16.CHR
pUS(12C)180d_T2_0.1ml
TC


"C02",3.962,13976.5908,1687.549,1.7900,""
