Templeton
Templeton
N2024


10/13/2022 17:34:07
Syringe Injection

FID
2m 2mmID ShinCarbonST 80/100
Argon at 35psi
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_200deg.tem
Channel1.evt
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_iso_FID_comps.cpt
60.0,40.0,   10.00, 1.000, 0.500,0
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_Ar_iso200_35psi.CON
13OCT22FID_TC_09.CHR
pUS(12C)30d_0.5ml
TC


"C02",3.900,183.6778,21.961,0.0235,""
