Templeton
Templeton
N2024


09/30/2022 15:23:23
Syringe Injection

TCD
2m 2mmID ShinCarbonST 80/100
Argon at 35psi

ch2.evt
TC_iso_TCD_comps.cpt
60.0,40.0,    1.00, 1.000, 0.500,0
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_Ar_iso200_35psi.CON
30Sept22TCD_TC_23.CHR
0.5mL_NT-Core-Test_Failed
TC


"H2",1.939,10.9127,1.129,0.0014,""
"O2",2.365,8.5987,1.277,0.0000,""
