Templeton
Templeton
N2024


10/28/2022 21:30:13
Syringe Injection

FID
2m 2mmID ShinCarbonST 80/100
Argon at 35psi
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_200deg.tem
Channel1.evt
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_iso_FID_comps.cpt
60.0,40.0,   10.00, 1.000, 0.500,0
K:\Templeton_Lab\SRI GC files\Peak426-32bit\TC_Ar_iso200_35psi.CON
28OCT22FID_TC_32.CHR
p83m(12C)30d_0.5ml
TC


"C02",3.960,1510.1418,168.256,0.1934,""
